apiVersion: v1
kind: Service
metadata:
  name: mon-flask-app
spec:
  type: NodePort
  selector:
    app: mon-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007